variables:
  RV: 'crownet/scripts'
# Tags of all containers required for building and testing
# Note: Tags here must include ALL container tags required in the fingerprint
#       *.csv and *.yml files.
  INETBRANCH: 'v4.5.2'
  BUILDMODE: 'release'
  CROWNET_IMAGE_REG: '${CI_REGISTRY}'
  CROWNET_IMAGE_BASE: '${CROWNET_IMAGE_REG}/rover/crownet'
  CROWNET_OPP_CONT_TAG: '6.0.3'  #tag of OMNeT++ container to be used

  CROWNET_IMAGE_REG: '${CI_REGISTRY}'
  CROWNET_IMAGE_BASE: '${CROWNET_IMAGE_REG}/rover/crownet'

stages:
  - build
  - test

# this job
# - prepares the environment
#   (pulls required docker containers, clones and builds inet)
# - builds the simu5g project itself
Build:
  stage: build
  before_script:
    # docker login asks for the password to be passed through stdin for security
    # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY/rover/crownet/omnetpp:${CROWNET_OPP_CONT_TAG}
  script:
    - "mkdir .tmp"
    - "mv * .tmp"
    - "git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@sam-dev.cs.hm.edu/rover/crownet.git"
    - "mv .tmp simu5g"
    - "git clone --branch ${INETBRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@sam-dev.cs.hm.edu/rover/inet.git inet4"
    - "cd inet4"
    - "../$RV/omnetpp ${CROWNET_OPP_CONT_TAG} exec \"source setenv && make makefiles\""
    - "../$RV/omnetpp ${CROWNET_OPP_CONT_TAG} exec \"source setenv && make -j16 MODE=${BUILDMODE}\"; TEST_STATUS=${PIPESTATUS[0]}"
    # we do not need the inet sources anymore - delete them to have less artifacts
    - "find . -name \"*.cc\" -type f -delete"
    # build simu5g itself
    - "cd ../simu5g"
    - "../$RV/omnetpp ${CROWNET_OPP_CONT_TAG} exec make makefiles"
    - "../$RV/omnetpp ${CROWNET_OPP_CONT_TAG} exec make -j16 MODE=${BUILDMODE}"
  artifacts:
    paths:
    # we keep the scripts
    - crownet/scripts
    # we need to keep the ned files and the simu5g lib
    - simu5g
    # we need to keep the ned files and the inet lib (all stored in the src subfolder)
    - inet4/src
    expire_in: 2 weeks

# This job runs the fingerprint tests
Fingerprints:
  stage: test
  script:
    - "cd simu5g/tests/fingerprint"
    - "../../../../$RV/omnetpp ${CROWNET_OPP_CONT_TAG} exec ./fingerprints"
  artifacts:
    paths:
    - simu5g/tests/fingerprint
    expire_in: 2 weeks
    